from typing import Literal

LANGUAGES = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic (العربية)',
    'hy': 'armenian (հայերեն)',
    'az': 'azerbaijani (azərbaycan)',
    'eu': 'basque (euskara)',
    'be': 'belarusian (беларуская)',
    'bn': 'bengali (বাংলা)',
    'bs': 'bosnian (bosanski)',
    'bg': 'bulgarian (български)',
    'ca': 'catalan (català)',
    'ceb': 'cebuano (cebuano)',
    'ny': 'chichewa (chichewa)',
    'zh-cn': 'chinese (simplified) (中文)',
    'zh-tw': 'chinese (traditional) (中文)',
    'co': 'corsican (corsu)',
    'hr': 'croatian (hrvatski)',
    'cs': 'czech (čeština)',
    'da': 'danish (dansk)',
    'nl': 'dutch (nederlands)',
    'en': 'english (english)',
    'eo': 'esperanto (esperanto)',
    'et': 'estonian (eesti)',
    'tl': 'filipino (filipino)',
    'fi': 'finnish (suomi)',
    'fr': 'french (français)',
    'fy': 'frisian (frysk)',
    'gl': 'galician (galego)',
    'ka': 'georgian (ქართული)',
    'de': 'german (deutsch)',
    'el': 'greek (ελληνικά)',
    'gu': 'gujarati (ગુજરાતી)',
    'ht': 'haitian creole (kreyòl ayisyen)',
    'ha': 'hausa (hausa)',
    'haw': 'hawaiian (ʻōlelo hawaiʻi)',
    'he': 'hebrew (עברית)',
    'hi': 'hindi (हिन्दी)',
    'hmn': 'hmong (hmong)',
    'hu': 'hungarian (magyar)',
    'is': 'icelandic (íslenska)',
    'ig': 'igbo (igbo)',
    'id': 'indonesian (bahasa indonesia)',
    'ga': 'irish (gaeilge)',
    'it': 'italian (italiano)',
    'ja': 'japanese (日本語)',
    'jw': 'javanese (basa jawa)',
    'kn': 'kannada (ಕನ್ನಡ)',
    'kk': 'kazakh (қазақ тілі)',
    'km': 'khmer (ខ្មែរ)',
    'ko': 'korean (한국어)',
    'ku': 'kurdish (kurdî)',
    'ky': 'kyrgyz (кыргызча)',
    'lo': 'lao (ລາວ)',
    'la': 'latin (latina)',
    'lv': 'latvian (latviešu)',
    'lt': 'lithuanian (lietuvių)',
    'lb': 'luxembourgish (lëtzebuergesch)',
    'mk': 'macedonian (македонски)',
    'mg': 'malagasy (malagasy)',
    'ms': 'malay (bahasa melayu)',
    'ml': 'malayalam (മലയാളം)',
    'mt': 'maltese (malti)',
    'mi': 'maori (te reo māori)',
    'mr': 'marathi (मराठी)',
    'mn': 'mongolian (монгол)',
    'my': 'myanmar (burmese) (မြန်မာ)',
    'ne': 'nepali (नेपाली)',
    'no': 'norwegian (norsk)',
    'ps': 'pashto (پښتو)',
    'fa': 'persian (فارسی)',
    'pl': 'polish (polski)',
    'pt': 'portuguese (português)',
    'pa': 'punjabi (ਪੰਜਾਬੀ)',
    'ro': 'romanian (română)',
    'ru': 'russian (русский)',
    'sm': 'samoan (gagana samoa)',
    'gd': 'scots gaelic (gàidhlig)',
    'sr': 'serbian (српски)',
    'st': 'sesotho (sesotho)',
    'sn': 'shona (shona)',
    'sd': 'sindhi (سنڌي)',
    'si': 'sinhala (සිංහල)',
    'sk': 'slovak (slovenčina)',
    'sl': 'slovenian (slovenščina)',
    'so': 'somali (soomaali)',
    'es': 'spanish (español)',
    'su': 'sundanese (basa sunda)',
    'sw': 'swahili (kiswahili)',
    'sv': 'swedish (svenska)',
    'tg': 'tajik (тоҷикӣ)',
    'ta': 'tamil (தமிழ்)',
    'te': 'telugu (తెలుగు)',
    'th': 'thai (ไทย)',
    'tr': 'turkish (türkçe)',
    'ur': 'urdu (اردو)',
    'uz': 'uzbek (oʻzbek)',
    'vi': 'vietnamese (tiếng việt)',
    'cy': 'welsh (cymraeg)',
    'xh': 'xhosa (isiXhosa)',
    'yi': 'yiddish (ייִדיש)',
    'yo': 'yoruba (yorùbá)',
    'zu': 'zulu (isiZulu)'
}
